apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- bluegreen.yaml
- canary.yaml
- ingress.yaml
- hpa.yaml
configMapGenerator:
- name: app-config
  literals:
  - APP_ENV=dev
  - APP_VERSION=v1.0.0
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.io/DOCKERHUB_USER/lab-api
  newTag: v1.0.0
