apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
namespace: lab-devops-dev
patches:
- path: patch-service-green.yaml
- target:
    kind: Ingress
    name: lab-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.lab.local
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - APP_ENV=dev
  - APP_VERSION=v1.0.1
images:
- name: docker.io/brenofrancoa/lab-api
  newTag: v1.0.1
